version: '3.4'

services:
  foodorderingsystem.webapi:
    image: ${DOCKER_REGISTRY-}foodorderingsystemwebapi
    container_name: foodorderings.api
    build:
      context: .
      dockerfile: FoodOrderingSystem.WebAPI/Dockerfile
    ports:
        - 5000:5000
        - 5001:5001
    
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root-root
        MONGO_INITDB_DATABASE: foodorderingsystemdb
    ports:
        - 27017:27017

